import os

ROOT_DIR = "."
OUTPUT_FILE = "index.html"

def generate():
    links = []

    for root, dirs, files in os.walk(ROOT_DIR):
        # bỏ folder không cần
        dirs[:] = [d for d in dirs if d not in [".git", ".github"]]

        for file in files:
            if file.endswith(".html") and file != "index.html":
                full_path = os.path.join(root, file)
                rel_path = os.path.relpath(full_path, ROOT_DIR)
                links.append(rel_path.replace("\\", "/"))

    links.sort()

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("""<!DOCTYPE html>
<html lang="vi">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>My Knowledge</title>

<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap" rel="stylesheet">

<style>
body {
    font-family: 'Inter', sans-serif;
    background: #f5f7fb;
    margin: 0;
    padding: 40px;
    color: #1f2937;
}

.container {
    max-width: 900px;
    margin: auto;
}

h1 {
    font-weight: 600;
    margin-bottom: 20px;
}

.search {
    width: 100%;
    padding: 12px;
    border-radius: 10px;
    border: 1px solid #ddd;
    margin-bottom: 20px;
    font-size: 14px;
}

.grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(220px, 1fr));
    gap: 16px;
}

.card {
    background: white;
    padding: 16px;
    border-radius: 14px;
    text-decoration: none;
    color: inherit;
    box-shadow: 0 4px 12px rgba(0,0,0,0.05);
    transition: 0.2s;
}

.card:hover {
    transform: translateY(-4px);
    box-shadow: 0 8px 20px rgba(0,0,0,0.08);
}

.card-title {
    font-size: 14px;
    font-weight: 500;
    word-break: break-word;
}

.footer {
    margin-top: 40px;
    font-size: 12px;
    color: #888;
}
</style>
</head>

<body>
<div class="container">
<h1>My Knowledge</h1>

<input class="search" placeholder="Search..." oninput="filterCards(this.value)">

<div class="grid" id="grid">
""")

        for link in links:
            name = link.split("/")[-1].replace(".html", "")
            f.write(f'''
<a class="card" href="{link}">
    <div class="card-title">{name}</div>
</a>
''')

        f.write("""
</div>

<div class="footer">
Auto generated by GitHub Actions
</div>

</div>

<script>
function filterCards(q) {
    q = q.toLowerCase();
    const cards = document.querySelectorAll('.card');

    cards.forEach(card => {
        const text = card.innerText.toLowerCase();
        card.style.display = text.includes(q) ? 'block' : 'none';
    });
}
</script>

</body>
</html>
""")

if __name__ == "__main__":
    generate()
